#!/bin/bash

set -ue

# usage:
# package_payload package_name packaged_folder

# This will create a new packaged version of `package_name', which will extract
# all files which in `packaged_folder' into a temporary folder, and run
# `temp_dir/bin/package_name', so, it requires `packaged_folder/bin/package_name'
# must exists and can be run correctly

package_name=$1
packaged_folder=$2
stripped_package_name=$(basename $package_name)
tar_file=$(mktemp)

# Copy from https://stackoverflow.com/a/77679184/749774
# package the packaged folder into a tar file, frozen the time to to fixed 1970-01-01 08:00:00
# which make created tarball base64 never changed if not change original code.
(
    builtin cd "$packaged_folder" &>/dev/null &&
        tar --sort=name \
            --mtime="1970-01-01 08:00:00" \
            --owner=0 --group=0 --numeric-owner \
            --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
            -zcvf $tar_file .
)

# Compute payload metadata
payload_sha256="$(sha256sum "$tar_file" | awk '{print $1}')"

# # 删除源文件的 payload
# # sed /q keep match line,  /Q not keep
# sed -i '/^PAYLOAD:$/Q' $package_name

cat <<HEREDOC > $package_name
#!/bin/sh

set -e

if [ -z "\$BASH_VERSION" ]; then
    if test -h /bin/ls && [[ \$(readlink /bin/ls) =~ busybox ]]; then
        true
    else
        exec bash "\$0" "\$@"
    fi
fi

# hack for install dte into remote vps only, don't user this for others purpose.
if [[ "\$1" =~ .*@[0-9.]+\$ ]]; then
    scp \$0 "\$1":/usr/local/bin
    ssh "\$1" "[ -e .bashrc ] && cat .bashrc |grep -F -qs -e 'alias e=' || echo -e \"alias e=dte\nexport EDITOR=dte\nexport VISUAL=dte\" >> .bashrc"
    ssh "\$1"
    exit
fi

payload_line_num=\$(grep -a -m1 -n '^__PAYLOAD__:\$' "\$0" | cut -d: -f1)
combined_hash=\$(head -n "\$payload_line_num" "\$0" | sha256sum | awk '{print \$1}')
# payload_offset = 文件前 N 行 到 __PAYLOAD__: 这一行结束 (冒号) 为止的字节数
payload_offset=\$(head -n "\$payload_line_num" "\$0" | wc -c)

running_dir="\${HOME:-/tmp}/.cache/$stripped_package_name/\$combined_hash"

if [ ! -d \$running_dir ]; then
    mkdir -p \$running_dir

    # 这个方案在 busybox 下不工作，因为他不支持 count 以 B 作为单位。
    # dd if=\$0 of=\$running_dir/payload.tgz bs=1M skip=\${payload_offset}B count=\${payload_size}B status=none

    tail -c +\$((payload_offset + 1)) \$0 > \$running_dir/payload.tgz

    echo "$payload_sha256  \$running_dir/payload.tgz" | sha256sum -c - >/dev/null

    tar -zxf \$running_dir/payload.tgz -C \$running_dir

    rm "\$running_dir/payload.tgz"
fi

binary_path="\$running_dir/bin/$stripped_package_name"

chmod +x "\$binary_path"


# 下面的 printf 和 exec -a, 做双重保证，确保命令行的 title 显示打包的 binary 的名称，例如: dte
printf '\033]0;'$stripped_package_name'\007'

function restore_title() {
  printf '\033]0;%s\007' "bash"
}

trap restore_title EXIT

"\$binary_path" "\$@"

exit 0

__PAYLOAD__:
HEREDOC

chmod +x $package_name

# 直接把二进制 tar.gz append 到脚本末尾
cat $tar_file >> $package_name
