#!/bin/bash

set -ue

# usage:
# package_payload package_name packaged_folder

# This will create a new packaged version of `package_name', which will extract
# all files which in `packaged_folder' into a temporary folder, and run
# `temp_dir/bin/package_name', so, it requires `packaged_folder/bin/package_name'
# must exists and can be run correctly

package_name=$1
packaged_folder=$2
stripped_package_name=$(basename $1)
tar_file=$(mktemp)

# Copy from https://stackoverflow.com/a/77679184/749774
# package the packaged folder into a tar file, frozen the time to to fixed 1970-01-01 08:00:00
# which make created tarball base64 never changed if not change original code.
(
    builtin cd "$packaged_folder" &>/dev/null &&
        tar --sort=name \
            --mtime="1970-01-01 08:00:00" \
            --owner=0 --group=0 --numeric-owner \
            --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
            -zcvf $tar_file .
)

# # 删除源文件的 payload
# # sed /q keep match line,  /Q not keep
# sed -i '/^PAYLOAD:$/Q' $package_name

cat <<HEREDOC > $package_name
#!/bin/sh

set -e

if [ -z "\$BASH_VERSION" ]; then
    if test -h /bin/ls && [[ \$(readlink /bin/ls) =~ busybox ]]; then
        true
    else
        exec bash "\$0" "\$@"
    fi
fi

# hack for install dte into remote vps only, don't user this for others purpose.
if [[ "\$1" =~ .*@[0-9.]+\$ ]]; then
    scp \$0 "\$1":/usr/local/bin
    ssh "\$1" "[ -e .bashrc ] && cat .bashrc |grep -F -qs -e 'alias e=' || echo -e \"alias e=dte\nexport EDITOR=dte\nexport VISUAL=dte\" >> .bashrc"
    ssh "\$1"
    exit
fi
payload_start_line=\$((\$(grep -n '^PAYLOAD:\$' \$0 | cut -d ':' -f 1) + 1))
running_dir=\$(mktemp -d)
if [ ! -d \$running_dir/local ]; then
    mkdir -p \$running_dir/local
    echo "\$(tail -n +\${payload_start_line} \$0)" |base64 -d |tar -zxf - -C \$running_dir/local
fi
chmod +x \$running_dir/local/bin/$stripped_package_name


# 下面的 printf 和 exec -a, 做双重保证，确保命令行的 title 显示打包的 binary 的名称，例如: dte
printf '\033]0;'$stripped_package_name'\007'

function restore_title() {
  printf '\033]0;%s\007' "bash"
}

trap restore_title EXIT

\$running_dir/local/bin/$stripped_package_name "\$@"

exit 0

PAYLOAD:
HEREDOC

chmod +x $package_name

cat $tar_file |base64 >> $package_name
